# -*- coding: utf-8 -*-
"""exercicios for

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fueBA8BDC0g-V3Evts-liua5B0XHeAxZ

Faça um programa que receba dois números inteiros e gere os números inteiros
que estão no intervalo compreendido por eles.
"""

numero_1 = int(input("digite um numero inteiro?: "))
numero_2 = int(input("digite outro numero inteiro?: "))

for i in range(numero_1,numero_2):
  print(i)

"""2. Altere o programa anterior para mostrar no final a soma dos números."""

numero_1 = int(input("digite um numero inteiro?: "))
numero_2 = int(input("digite outro numero inteiro?: "))
contador = 1
for contador in range(numero_1,numero_2):
  print(contador)