# -*- coding: utf-8 -*-
"""FOR N

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLq85tYHDd138_HqkGNm1Vi5uCWatY17

faça um programa que leia 5 numeros e informe o maior numero.
"""

maior_numero = float
for banana in range(5):
  numero = float

"""faça  um programa que verifique e mostre os numeros entre 1000 e 2000 (INCLUSIVE) que , divididos por 11 tenha um resto 2"""

for numero in range(1000,2001):
    if numero % 11 == 2:
        print(numero)

"""Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número.

"""

numero = int(input("Digite um número para ver sua tabuada: "))

print(f"Tabuada de {numero}:")
for contador in range(1, 11):
    resultado = numero * i
    print(f"{numero} x {contador} = {resultado}")

"""faça um programa que imprima na tela os numeros de 1 a 20,um abaixo do outro.depois modifique o programa  para que ele mostre os numeros um ao lado do outro."""

for i in range(1,21):
  print(i)
print(list(range(1,21)))